#!/bin/bash
cd $1"_0"
python3 run-rr.py 0 16 $2 &> out &
cd ..
cd $1"_1"
python3 run-rr.py 1 16 $2 &> out &
cd ..
cd $1"_2"
python3 run-rr.py 2 16 $2 &> out &
cd ..
cd $1"_3"
python3 run-rr.py 3 16 $2 &> out &
cd ..
cd $1"_4"
python3 run-rr.py 4 16 $2 &> out &
cd ..
cd $1"_5"
python3 run-rr.py 5 16 $2 &> out &
cd ..
cd $1"_6"
python3 run-rr.py 6 16 $2 &> out &
cd ..
cd $1"_7"
python3 run-rr.py 7 16 $2 &> out &
cd ..
cd $1"_8"
python3 run-rr.py 8 16 $2 &> out &
cd ..
cd $1"_9"
python3 run-rr.py 9 16 $2 &> out &
cd ..
cd $1"_10"
python3 run-rr.py 10 16 $2 &> out &
cd ..
cd $1"_11"
python3 run-rr.py 11 16 $2 &> out &
cd ..
cd $1"_12"
python3 run-rr.py 12 16 $2 &> out &
cd ..
cd $1"_13"
python3 run-rr.py 13 16 $2 &> out &
cd ..
cd $1"_14"
python3 run-rr.py 14 16 $2 &> out &
cd ..
cd $1"_15"
python3 run-rr.py 15 16 $2 &> out &
cd ..
wait
